# -*- mode: python ; coding: utf-8 -*-
"""PyInstaller spec for the Qt edition.

Build from the repository root:

    pip install -e ".[dev]"
    python tools/build_mo.py            # translations must exist first
    python tools/gen_version_build.py   # stamps the build number from git
    pyinstaller -y packaging/pdfarranger-qt.spec

Or just run `packaging/build_win` (bash) / `packaging\\build_win.bat` (cmd),
which does all four and then builds the installer.
"""

import os
import sys
import re

project_root = os.path.abspath(os.path.join(SPECPATH, ".."))

# ---------------------------------------------------------------- version ----
# The base version lives in the package, exactly once; pyproject.toml is held to
# it by tests/test_packaging.py. The build number is the git commit count,
# written by tools/gen_version_build.py and not committed.
init_py = os.path.join(project_root, "pdfarranger_qt", "__init__.py")
with open(init_py, encoding="utf-8") as handle:
    version = re.search(r'^__version__ = "([^"]+)"', handle.read(), re.M).group(1)

build_file = os.path.join(project_root, "pdfarranger_qt", "version_build")
if os.path.isfile(build_file):
    with open(build_file, encoding="utf-8") as handle:
        build = handle.read().strip() or "0"
else:
    # A bare `pyinstaller` run without the build script. Not fatal, but the
    # About box would claim a build number of 0, so say so.
    print("WARNING: pdfarranger_qt/version_build is missing - run "
          "tools/gen_version_build.py; using 0")
    build = "0"

package_version = f"{version}.{build}"
print(f"Creating build for version {package_version}")

# ------------------------------------------------------------------ datas ----
datas = []

# Compiled catalogues. The application looks in share/locale first (see
# i18n.locale_dirs), so they ship there rather than in build/mo.
mo_root = os.path.join(project_root, "build", "mo")
if os.path.isdir(mo_root):
    for language in sorted(os.listdir(mo_root)):
        catalogue = os.path.join(mo_root, language, "LC_MESSAGES", "pdfarranger.mo")
        if os.path.isfile(catalogue):
            datas.append((catalogue, os.path.join("share", "locale", language,
                                                  "LC_MESSAGES")))
else:
    print("WARNING: build/mo is missing - run tools/build_mo.py for translations")

icon_ico = os.path.join(project_root, "data", "pdfarranger.ico")
if os.path.isfile(icon_ico):
    datas.append((icon_ico, "."))

# macOS: generated by packaging/make_icns.sh rather than committed, so there is
# no second copy of the artwork to keep in step with data/icons.
icon_icns = os.path.join(project_root, "build", "pdfarranger-qt.icns")

# Read back at runtime by pdfarranger_qt._read_build() via sys._MEIPASS.
if os.path.isfile(build_file):
    datas.append((build_file, "."))

# ------------------------------------------------------------ version info ---
# Windows only: puts the version on the exe's Properties tab, and gives Inno
# Setup something to compare when replacing an older install.
version_resource = None
if os.name == "nt":
    from PyInstaller.utils.win32.versioninfo import (
        FixedFileInfo, StringFileInfo, StringStruct, StringTable, VarFileInfo,
        VarStruct, VSVersionInfo,
    )

    # The Windows resource wants exactly four integers.
    numbers = tuple(int(part) for part in package_version.split("."))
    numbers += (0,) * (4 - len(numbers))

    version_resource = VSVersionInfo(
        ffi=FixedFileInfo(filevers=numbers, prodvers=numbers,
                          mask=0x3F, flags=0x0, OS=0x40004, fileType=0x1,
                          subtype=0x0, date=(0, 0)),
        kids=[
            StringFileInfo([StringTable("040904B0", [
                StringStruct("CompanyName", "Dolce Sfogato"),
                StringStruct("FileDescription",
                             "Merge, split, rearrange, rotate and crop PDF documents"),
                StringStruct("FileVersion", package_version),
                StringStruct("InternalName", "pdfarranger-qt"),
                StringStruct("LegalCopyright",
                             "Copyright (C) 2026 pdfarranger-qt contributors. "
                             "GPL-3.0-or-later."),
                StringStruct("OriginalFilename", "pdfarranger-qt.exe"),
                StringStruct("ProductName", "PDF Arranger Qt"),
                StringStruct("ProductVersion", package_version),
            ])]),
            # 0x0409 = US English, 1200 = Unicode.
            VarFileInfo([VarStruct("Translation", [0x0409, 1200])]),
        ],
    )

# ------------------------------------------------------------------ build ----
a = Analysis(
    [os.path.join(project_root, "pdfarranger_qt", "__main__.py")],
    pathex=[project_root],
    binaries=[],
    datas=datas,
    # QtPdf is loaded through PySide6 rather than imported by name, and img2pdf
    # pulls its image backends in lazily.
    hiddenimports=["PySide6.QtPdf", "PySide6.QtPrintSupport", "img2pdf"],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    # Nothing here uses these, and they are large.
    excludes=["tkinter", "PySide6.QtWebEngineCore", "PySide6.QtQuick",
              "PySide6.Qt3DCore", "PySide6.QtCharts", "PySide6.QtMultimedia",
              "gi", "cairo", "matplotlib", "numpy.f2py"],
    noarchive=False,
)

pyz = PYZ(a.pure)

if sys.platform == "darwin":
    icon = icon_icns if os.path.isfile(icon_icns) else None
else:
    icon = icon_ico if os.path.isfile(icon_ico) else None

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name="pdfarranger-qt",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    console=False,  # GUI application: no console window
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    # Opt-in, and read from the environment rather than hardcoded: this is a
    # public repository and a Developer ID does not belong in it. See
    # packaging/build_mac.
    codesign_identity=os.environ.get("CODESIGN_IDENTITY") or None,
    entitlements_file=None,
    icon=icon,
    version=version_resource,
)

coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=False,
    upx_exclude=[],
    name="pdfarranger-qt",
)

if sys.platform == "darwin":
    app = BUNDLE(
        coll,
        name="PDF Arranger Qt.app",
        icon=icon_icns if os.path.isfile(icon_icns) else None,
        bundle_identifier="com.dolcesfogato.pdfarranger-qt",
        version=package_version,
        info_plist={
            "CFBundleName": "PDF Arranger Qt",
            "CFBundleDisplayName": "PDF Arranger Qt",
            "CFBundleVersion": package_version,
            "CFBundleShortVersionString": package_version,
            "NSPrincipalClass": "NSApplication",
            "NSAppleScriptEnabled": False,
            "NSRequiresAquaSystemAppearance": "No",
            "NSHighResolutionCapable": "True",
            # Lets the Finder offer this app under "Open With" for PDFs, and
            # be set as the default handler. Note that opening one does *not*
            # arrive as a command-line argument, whatever this comment used to
            # claim: macOS sends an Apple Event, which Qt delivers as
            # QFileOpenEvent and `app.Application` listens for. Without that
            # handler the association works and double-clicking does nothing.
            "CFBundleDocumentTypes": [{
                "CFBundleTypeName": "PDF Document",
                "CFBundleTypeRole": "Editor",
                "LSHandlerRank": "Alternate",
                "LSItemContentTypes": ["com.adobe.pdf"],
            }],
        },
    )
